### PR TITLE
Correctly set GumTree system properties

### LINKED ISSUE #120: AstComparator appears to be setting the wrong system properties for GumTree
Hi!

I'm using `gumtree-spoon-ast-diff` for a structured merge tool as part of my thesis project (https://github.com/kth/spork), and when tampering with GumTree settings I noticed that the `AstComparator` class appears to be setting incorrect system properties, as they have changed in GumTree (i.e. they used to be correct but aren't anymore).

https://github.com/SpoonLabs/gumtree-spoon-ast-diff/blob/dae908192bee7773b38d149baff831ee616ec524/src/main/java/gumtree/spoon/AstComparator.java#L45

This appears to do nothing at all and the [default of 0.5 is always used](https://github.com/GumTreeDiff/gumtree/blob/556171f72b5cfeed767c9fc35054580c4ebe859f/core/src/main/java/com/github/gumtreediff/matchers/heuristic/gt/AbstractBottomUpMatcher.java#L39-L40). The correct property is [`gt.bum.smt`](https://github.com/GumTreeDiff/gumtree/wiki/Parameters).

https://github.com/SpoonLabs/gumtree-spoon-ast-diff/blob/dae908192bee7773b38d149baff831ee616ec524/src/main/java/gumtree/spoon/AstComparator.java#L50

This property [appears to still be respected](https://github.com/GumTreeDiff/gumtree/blob/556171f72b5cfeed767c9fc35054580c4ebe859f/core/src/main/java/com/github/gumtreediff/matchers/heuristic/gt/AbstractSubtreeMatcher.java#L34-L36), but I think that [`gt.stm.mh`](https://github.com/GumTreeDiff/gumtree/wiki/Parameters) is the one that should be used.

### PR DESCRIPTION
**Pull request by slarse**
Fix #120

See [GumTree parameters for the properties used here](https://github.com/GumTreeDiff/gumtree/wiki/Parameters)

### CODE REVIEW

**Comment by martinezmatias** [comment]
Dear @slarse 
Thanks for contributing to the project.
Could you provide a test case that exposes the bug (i.e. the no impact of that properties) and asserts the proposed patch fixes that problem?
I am not sure about the change. A test case could help to understand the problem. The reasons are (maybe I am wrong):
Even we set the variable `gumtree.match.gt.minh'
https://github.com/SpoonLabs/gumtree-spoon-ast-diff/blob/dae908192bee7773b38d149baff831ee616ec524/src/main/java/gumtree/spoon/AstComparator.java#L45
then, GumTree takes this variable and put it in `gt.stm.mh'.
As you proposed, to putting directly a value on property  `gt.stm.mh' could be a solution.
WDYT?

**Comment by slarse** [comment]
Test case coming up in a minute!

**Comment by martinezmatias** [comment]
> Test case coming up in a minute!
Great. An ideal test  should:  a) fail on the no patched version of the tool, b) pass on the patched version.

**Comment by slarse** [comment]
The test case in 44b1a16 will fail for the unpatched version.

I would however refactor this such that `AstComparator` exposes the settings as static final variables, such that the values aren't hard coded in the test case.

**Comment by slarse** [comment]
To be clear, the problem is that previously, the property `gumtree.match.bu.sim` did do something:

https://github.com/GumTreeDiff/gumtree/blob/fb93319b5e096829c0277d8c39582433095e0173/core/src/main/java/com/github/gumtreediff/matchers/heuristic/gt/GreedyBottomUpMatcher.java#L36

But not anymore:

https://github.com/GumTreeDiff/gumtree/blob/556171f72b5cfeed767c9fc35054580c4ebe859f/core/src/main/java/com/github/gumtreediff/matchers/heuristic/gt/GreedyBottomUpMatcher.java#L34-L67

Now, the default value from `AbstractBottomUpMatcher` is used: 
https://github.com/GumTreeDiff/gumtree/blob/556171f72b5cfeed767c9fc35054580c4ebe859f/core/src/main/java/com/github/gumtreediff/matchers/heuristic/gt/AbstractBottomUpMatcher.java#L39-L40

**Comment by slarse** [comment]
On that note, perhaps the test case should actually check the value in `GreedyBottomUpMatcher` instead of in `AbstractBottomUpMatcher`, as there have been discrepancies between the two in the past.

**Comment by martinezmatias** [comment]
Dear @slarse 
Thanks for the test and the explanation about the evolution of the use of that property.
A proposed test case would test: if you change the property now it has an impact on the diff results. Before the patch, it did not have any impact.
WDYT?

**Comment by slarse** [comment]
Hmm, I'm not sure how to test that. The property is loaded once and only once in static code and set in a final variable, in order to test different values of the property one would need to restart the JVM.

**Comment by martinezmatias** [comment]
> Hmm, I'm not sure how to test that. The property is loaded once and only once in static code and set in a final variable, in order to test different values of the property one would need to restart the JVM.

I agree that the design of GT does not allow to easily change these properties.

That's right.

> That seems like a test case for the GumTree libarary, rather than this one. Here, we're really only interested in the properties we think are set to actually be set as we expect. I don't think it matters if we aren't actively setting them, as long as they have the values we expect them to.

**Comment by slarse** [comment]
But I totally agree that the test case is pretty weak, I just don't have any other ideas :D

**Comment by slarse** [comment]
Perhaps there is a way to start specific test cases in their own JVMs, but that exceeds my JUnit and Maven knowledge.

**Comment by martinezmatias** [comment]
> But I totally agree that the test case is pretty weak, I just don't have any other ideas :D
You have found a complex issue, we really appreciate that.

Beyond not having particular a test case for testing that, the patch does not affect the existing cases.

Ok for merging?

**Comment by slarse** [comment]
@martinezmatias If you're satisfied with the changes then go ahead!

**Comment by martinezmatias** [comment]
It's fine for me. I will think about the way to test that.
FYI: I will be at KTH around the April, 15. We can discuss there.
Thanks a lot for the contribution!

**Comment by slarse** [comment]
> FYI: I will be at KTH around the April, 15. We can discuss there.

Sounds good, marked it 

> Thanks a lot for the contribution!

Happy I could help, this library is saving me a lot of time with my thesis project (or rather, makes it possible) so it's nice to be able to contribute back.

**Pull request merged**
