### PR TITLE
test: upgrade test suite to use latest JUnit version

### LINKED ISSUE #227: Migrate test suite to JUnit5
Same rationale as https://github.com/INRIA/spoon/issues/3919#issue-887351734 behind this issue.

We can use [laughing-train](https://github.com/MartinWitt/laughing-train) (@MartinWitt's initiative) to transform the imports and their uses. For more thorough use of Junit5, we can combine some tests using `@Nested`. For example, https://github.com/SpoonLabs/gumtree-spoon-ast-diff/blob/master/src/test/java/gumtree/spoon/diff/DiffTest.java#L203-L231.

### How to use [laughing-train](https://github.com/MartinWitt/laughing-train)

Refer to the comment [here](https://github.com/INRIA/spoon/pull/4400#issuecomment-1006918035).

### PR DESCRIPTION
**Pull request by algomaster99**
Fixes #227 

I need to upgrade in order to write good tests. I could use https://github.com/MartinWitt/laughing-train for this problem, but I was not able to build it on my system :/ 

The refactoring was pretty straightforward. I changed import statements, `Ignore` is now called `Disabled`, and `reason` argument is not the last - after `expected` and `actual`.

### CODE REVIEW

**Comment by algomaster99** [comment]
This PR is a reminder that even the simplest of problems can take a bit of your time :cry: 

The only test that fails it is because of a diff `UPDATE: TestCase to junit.framework.TestCase`. In the left version, [`TestCase` is imported using wildcard](https://github.com/SpoonLabs/gumtree-spoon-ast-diff/blob/847222c6f11566e440826ba3d6bc8755c3a7b05b/src/test/resources/examples/t_224834/left_TestPriorityQueue_1.2.java#L59-L61) and in the right version, [`TestCase` is imported using its fully qualified name](https://github.com/SpoonLabs/gumtree-spoon-ast-diff/blob/847222c6f11566e440826ba3d6bc8755c3a7b05b/src/test/resources/examples/t_224834/right_TestPriorityQueue_1.3.java#L59).

With JUnit4 in the classpath, gumtree-spoon resolves that `TestCase` is same as `junit.framework.TestCase` since `junit.framework,TestCase` is an API from JUnit4. However, when we update the JUnit version, spoon model cannot infer the same. 

@MartinWitt @I-Al-Istannen, did you see such a bug when porting JUnit 4 to JUnit 5 in spoon?

**Comment by algomaster99** [comment]
@SirYwell do you have an idea about this?

**Comment by SirYwell** [comment]
So in one version the class can be resolved via reflections and in the other spoon uses the no-classpath mode to try to come up with something? I don't think we encountered that in the spoon tests.

But I don't see a way that allows us - while using wildcard imports - to resolve the class properly. I assume you either have to adjust the resources, or the test, or the dependencies.

**Comment by algomaster99** [comment]
> one version the class can be resolved via reflections and in the other spoon uses the no-classpath mode

It seems we use Spoon in default mode as you can see [here](https://github.com/SpoonLabs/gumtree-spoon-ast-diff/blob/f5e6ff26b770967dc2bd8ea877d07e340f713ca8/src/main/java/gumtree/spoon/AstComparator.java#L162). Not sure how mode is changing and if it should.
I will try isolating classes for gumtree-spoon diffs from the ones on classpath.

**Comment by algomaster99** [comment]
@monperrus the last few commits fix a failing test because of update in version. Reason: diff computation was taking the junit from classpath. Since it changed from 4 to 5, it caused a change in the diff.
Now, the test is rewritten to use `MavenLauncher` so it is forced to use junit 4 regardless of what is in the classpath.

You can merge now.

**Comment by algomaster99** [comment]
Hold on. There are some spurious changes.

**Comment by algomaster99** [comment]
Well, let's just live with it. Those are IntelliJ defaults. I don't want to change them.

**Comment by monperrus** [comment]
thanks @algomaster99

**Pull request merged**
