### PR TITLE
fix: Assertions in test 25008

### PR DESCRIPTION
**Pull request by surli**
When bumping to Spoon 6.0.0 an assert was changed to introduce a delete/insert changes in the diff, where it should have been a simple update. This should fix the CI.

### CODE REVIEW

**Comment by monperrus** [comment]
I've had a look at this. 

There are two strange things:

1) The assertion change was required and indeed worked for some time in CI

2) The test case succeeds when run in isolation but fails when the whole test suite is executed. This suggests there is some state somewhere, but I don't know where...

**Comment by surli** [comment]
> The assertion change was required and indeed worked for some time in CI

It might be related to the usage of a specific JDK: I did some test on jenkins yesterday and apparently the test suite was ok when switching to JDK 8.0.111 or something like that. However recent patches of JDK 8 break the test. I'll investigate.

**Comment by surli** [comment]
> The test case succeeds when run in isolation but fails when the whole test suite is executed

Which JDK did you use for your test? I just checked it back on my machine with a JDK 1.8.0.111 and 1.8.0.152 and both seems working here.

**Comment by surli** [comment]
@monperrus I cannot check on TravisCI here because there's an issue with the GPG key you configure. Could you fix that ?

**Comment by monperrus** [comment]
I don't understand. What do you try to do?

**Comment by surli** [comment]
The CI is currently failing with the following error: 
> $ openssl aes-256-cbc -K $encrypted_9809c3ea697e_key -iv $encrypted_9809c3ea697e_iv -in .buildscript/codesigning.asc.enc -out codesigning.asc -d
iv undefined
The command "openssl aes-256-cbc -K $encrypted_9809c3ea697e_key -iv $encrypted_9809c3ea697e_iv -in .buildscript/codesigning.asc.enc -out codesigning.asc -d" failed and exited with 1 during .

which is related to the following configuration on .travis.yml:
```yml
before_install:
# made with "travis encrypt-file codesigning.asc -r SpoonLabs/gumtree-spoon-ast-diff --add"
- openssl aes-256-cbc -K $encrypted_9809c3ea697e_key -iv $encrypted_9809c3ea697e_iv
  -in .buildscript/codesigning.asc.enc -out codesigning.asc -d
- gpg --fast-import codesigning.asc
``` 

I don't know how to fix this, but in the meantime I cannot see what is the status of this PR on Travis

**Comment by monperrus** [comment]
fixed travis.yml

**Comment by monperrus** [comment]
I'm reading on travis:

> This job is running on our Trusty environment, which has been updated on Tuesday, December 12th, 2017. Read all about this on our blog and take note that you can add group: deprecated-2017Q4 in your .travis.yml file to use the previous image version. 

this more or less corresponds to our first failure...

what about trying with `group: deprecated-2017Q4`?

**Comment by surli** [comment]
> what about trying with group: deprecated-2017Q4?

I don't really see the point if you fixed the travis.yml...

**Comment by monperrus** [comment]
I mean understanding the root of the newly failing assertion (not about the CI problem)

**Comment by monperrus** [comment]
can you trigger a new CI build with an empty commit? (I've restarted the PR build, it seems that the merge commit is not against the latest master)

**Comment by monperrus** [comment]
just triggered CI with Spoon 6.1.
it fails with both the normal travis image and with group: deprecated-2017Q4
https://travis-ci.org/SpoonLabs/gumtree-spoon-ast-diff/builds/326402576
https://travis-ci.org/SpoonLabs/gumtree-spoon-ast-diff/builds/326402443

so the cause is not JDK or Travis.

There is a hidden regression between 6.0 and 6.1.

**Comment by surli** [comment]
Just reproduced the bug on my machine: actually it does not occur with JDK 1.8.0_152 which seems to change some behaviour on final fields...

**Comment by monperrus** [comment]
> it does not occur with JDK 1.8.0_152 which seems to change some behaviour on final fields...
interesting...

**Comment by surli** [comment]
So... in order to understand what happens between running all tests and only test 25008, I tried to isolate it ... and I understand less than before what's going. 

As showing in classes TestWTF and TestWTF2, I obtained different results (passing or failing) according to:
- the number of tests in the test suite (even if the tests only contains assertEquals(1,1)) (it starts passing when the test suite contains more than 15 tests)
- if the test contain another test in ignore or not

If anyone has an idea there...

**Comment by surli** [comment]
And new funny thing: if I'm using the debugger I obtain always two actions. And it's officially not a flaky as I tried to launch the test in a loop and the result remains consistent. 😢

**Comment by surli** [comment]
So now it seems to be fixed on TravisCI but I continue to get failures on my machine. Anyone to try it on another machine to see what happens?

**Comment by monperrus** [comment]
Travis fails ;-)

**Comment by surli** [comment]
-_-'

**Comment by monperrus** [comment]
The good thing:

* the update to Spoon 6.1 improves the diff

The bad thing:

* we don't understand where the behavioral change is, what the root cause of the assertion failure is.

**Pull request merged**
