### PR TITLE
Wrong operation when insert `static` at a method head

### PR DESCRIPTION
**Pull request by 11510746**
https://github.com/SpoonLabs/gumtree-spoon-ast-diff/issues/86

### CODE REVIEW

**Comment by monperrus** [comment]
seems to me that it comes from wrong result of GT's `ActionGenerator`
@martinezmatias WDYT?

**Comment by martinezmatias** [comment]
It seems related to the bugfix I introduced for https://github.com/SpoonLabs/gumtree-spoon-ast-diff/issues/84

**Comment by martinezmatias** [comment]
It's strange the numbers of operations produced, all of them involving these new node I added

**Comment by martinezmatias** [comment]
I found the bug and a possible solution.
Bug: before we had  GumTree nodes *Modifiers* that grouped the modifiers of a CtModifiable (Method, class, param, field, etc). The last change I introduced added a Virtual Node for those modifiers that are not included in the spoon model, but that's not related to the bug (I think).
The problem is when matching modifiers: GT finds several of Trees with similar shape (i.e., Modifier root with child public), so in the buggy code it matches the modifiers of one CtElement (e.g., method) with those from another kind of elements (e.g., field).
Solution: to change the type of the GumTree nodes (and to the new virtual as well) that represent "Modifiers": instead of having only type Modifiers we add the class name of the CtModifiable. As consequence, Gumtree only will match modifiers that belong to the same CtElement.
Changes introduced in the PR.
WDYT? Merge?

**Pull request closed without merging**
