### PR TITLE
method for replacing moves by Insert/Deletes

### PR DESCRIPTION
**Pull request by martinezmatias**
Functionality created from @khaes-kth

### CODE REVIEW

**Comment by khaes-kth** [comment]
Thanks a lot for this incredibly fast implementation :)

Just one question: in the test case [where root operations are replaced](https://github.com/SpoonLabs/gumtree-spoon-ast-diff/blob/master/src/test/java/gumtree/spoon/AstComparatorTest.java#L1978), do you not think the result should have two operations? because when the if block is inserted, the "int z=0;" statement is inserted as a part of it. I think this makes the problem a bit complicated

**Comment by martinezmatias** [comment]
Hi @khaes-kth 
The second test case is different to the first one: The diff adds a new `If` and which is the new parent to the moved element.
So, 3 would be from: 1) the inserted If, 2) The delete of the moved  element, 3) The insert of the moved element

**Comment by martinezmatias** [comment]
W.r.t your point: the root groups the ops with the same type

**Comment by martinezmatias** [comment]
If we group in the roots the Insert with the moved, we are "losing" information

**Comment by martinezmatias** [comment]
In any case, in the new version I am refactoring the grouping of roots.

**Comment by khaes-kth** [comment]
> the root groups the ops with the same type


But as I understand, operation 1 and 3 (insertion of If and insertion of the moved element) are of the same type. It is true that Move is different from Insert in the old version of "diff" but now that we replace Move with Insert I think first and third operations should be grouped together.
WDYT?

**Comment by martinezmatias** [comment]
Sorry, I see your point. I got it now.
Let me think about it.

**Comment by martinezmatias** [comment]
Hi @khaes-kth 
This new commit should fix the issue you found.

**Comment by khaes-kth** [comment]
Great! It seems to work, thanks.

**Comment by martinezmatias** [comment]
Hi @khaes-kth 

> Great! It seems to work, thanks.

Perfect! tell me if you need more help with that.

Regards
Matias

**Pull request merged**
